prefix bibo:   <http://purl.org/ontology/bibo/>
prefix dct:    <http://purl.org/dc/terms/>
prefix dce:    <http://purl.org/dc/elements/1.1/>
prefix fabio:  <http://purl.org/spar/fabio/>
prefix foaf:   <http://xmlns.com/foaf/0.1/>
prefix issapr: <http://data-issa.cirad.fr/property/>
prefix oa:     <http://www.w3.org/ns/oa#>
prefix prov:   <http://www.w3.org/ns/prov#>
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
prefix xsd:    <http://www.w3.org/2001/XMLSchema#>

select ?descriptorText ?entityUri ?entityLabel
where {
    <{id}> a bibo:AcademicArticle, fabio:ResearchPaper.

    ?descriptor
        oa:hasTarget <{id}>;
        oa:hasBody ?entityUri.
    OPTIONAL { ?descriptor rdfs:label ?descriptorText. }
    OPTIONAL { ?entityUri rdfs:label ?entityLabel. FILTER ( lang(?entityLabel) = "en" ) }
}
