PREFIX bibo:   <http://purl.org/ontology/bibo/>
PREFIX dce:    <http://purl.org/dc/elements/1.1/>

SELECT *
FROM <http://data-issa.cirad.fr/graph/articles>
WHERE {
    <{id}>
        a bibo:AcademicArticle;
        dce:creator ?authors.
}
