PREFIX bibo:   <http://purl.org/ontology/bibo/>
PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX dce:    <http://purl.org/dc/elements/1.1/>
PREFIX fabio:  <http://purl.org/spar/fabio/>
PREFIX schema: <http://schema.org/>

SELECT *
FROM <http://data-issa.cirad.fr/graph/articles>
WHERE {
    <{id}> a bibo:AcademicArticle, fabio:ResearchPaper.

    OPTIONAL { <{id}> dct:title ?title.}
    OPTIONAL { <{id}> dct:issued ?date.}
    OPTIONAL { <{id}> schema:publication ?pub.}
    OPTIONAL { <{id}> dct:license ?license.}
    OPTIONAL { <{id}> bibo:doi ?doi.}
    OPTIONAL { <{id}> bibo:pmid ?pmid.}
    OPTIONAL { <{id}> fabio:hasPubMedId ?hasPubMedId.}
    OPTIONAL { <{id}> dct:source ?source.}
    OPTIONAL { <{id}> schema:url ?url.}
    OPTIONAL { <{id}> dce:language ?lang.}
    OPTIONAL { <{id}> dct:language ?lang2.}
    OPTIONAL { <{id}> dct:abstract [rdf:value ?abs].}
    OPTIONAL { <{id}> schema:downloadUrl ?linkPDF. }
}
