select ?descriptorText ?entityUri ?entityLabel
where {
    ?descriptor
        oa:hasTarget <{id}>;
        oa:hasBody ?entityUri.
    OPTIONAL { ?descriptor rdfs:label ?descriptorText. }
    OPTIONAL { ?entityUri rdfs:label ?entityLabel. FILTER ( lang(?entityLabel) = "en" ) }
}
