prefix bibo:   <http://purl.org/ontology/bibo/>
prefix dct:    <http://purl.org/dc/terms/>
prefix fabio:  <http://purl.org/spar/fabio/>
prefix oa:     <http://www.w3.org/ns/oa#>
prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
prefix skos:   <http://www.w3.org/2008/05/skos-xl>
prefix skosxl: <http://www.w3.org/2008/05/skos-xl#>

select ?entityUri ?entityLabel
where {
    <{id}> a bibo:AcademicArticle, fabio:ResearchPaper.

    ?descriptor
        oa:hasTarget <{id}>;
        oa:hasBody ?entityUri.

    OPTIONAL {
        ?entityUri rdfs:label|skos:prefLabel|(skosxl:prefLabel/skosxl:literalForm)|dct:title|schema:name ?entityLabel.
        FILTER(lang(?entityLabel) = "en")
    }
}
