prefix bibo:   <http://purl.org/ontology/bibo/>
prefix dct:    <http://purl.org/dc/terms/>
prefix dce:    <http://purl.org/dc/elements/1.1/>
prefix fabio:  <http://purl.org/spar/fabio/>
prefix foaf:   <http://xmlns.com/foaf/0.1/>
prefix issapr: <http://data-issa.cirad.fr/property/>
prefix oa:     <http://www.w3.org/ns/oa#>
prefix prov:   <http://www.w3.org/ns/prov#>
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
prefix xsd:    <http://www.w3.org/2001/XMLSchema#>

select ?entityText ?startPos ?endPos ?entityUri ?entityLabel
where {
    []  a oa:Annotation;
    oa:hasBody ?entityUri;
    oa:hasTarget ?z.

    ?z oa:hasSource <{id}>.
    OPTIONAL { ?z oa:hasSelector [oa:exact ?entityText]. }
    OPTIONAL { ?z oa:hasSelector [oa:start ?startPos]. }
    OPTIONAL { ?z oa:hasSelector [oa:end ?endPos]. }

    OPTIONAL { ?entityUri rdfs:label ?entityLabel. FILTER ( lang(?entityLabel) = "en" ) }
}
