PREFIX bibo:   <http://purl.org/ontology/bibo/>
PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX dce:    <http://purl.org/dc/elements/1.1/>
PREFIX prov:   <http://www.w3.org/ns/prov#>
PREFIX schema: <http://schema.org/>

SELECT ?uri ?title ?date ?publisher ?lang ?linkPDF (group_concat(distinct ?author, "$") as ?authors)
FROM <http://data-issa.cirad.fr/graph/documents>
FROM <http://data-issa.cirad.fr/graph/thematic-descriptors>
FROM <http://data-issa.cirad.fr/graph/annif-descriptors>
FROM <http://agrovoc.fao.org/graph>
WHERE {
    # Find documents who are the target of an annotation whose body is a specific URI
    ?uri a prov:Entity.

    # Add here one line for each descriptor, like this:
    #   ?document ^oa:hasTarget [ oa:hasBody <entityUri> ].
{id}

    OPTIONAL { ?uri dct:title ?title.}
    OPTIONAL { ?uri dce:creator ?author.}
    OPTIONAL { ?uri dct:issued ?date.}
    OPTIONAL { ?uri schema:publication ?publisher.}
    OPTIONAL { ?uri dce:language ?lang.}
    OPTIONAL { ?uri schema:downloadUrl ?linkPDF. }

} group by ?uri ?title ?date ?publisher ?lang ?linkPDF
limit 4000
