select *
where {
    OPTIONAL { {idArticle} dct:title ?title.}
    OPTIONAL { {idArticle} dct:issued ?date.}
    OPTIONAL { {idArticle} schema:publication ?pub.}
    OPTIONAL { {idArticle} dct:license ?license.}
    OPTIONAL { {idArticle} bibo:doi ?doi.}
    OPTIONAL { {idArticle} bibo:pmid ?pmid.}
    OPTIONAL { {idArticle} fabio:hasPubMedId ?hasPubMedId.}
    OPTIONAL { {idArticle} dct:source ?source.}
    OPTIONAL { {idArticle} schema:url ?url.}
    OPTIONAL { {idArticle} dce:language ?lang.}
    OPTIONAL { {idArticle} dct:language ?lang2.}
    OPTIONAL { {idArticle} dct:abstract [rdf:value ?abs].}
    OPTIONAL { {idArticle} schema:downloadUrl ?linkPDF. }
}
