PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
prefix oa: <http://www.w3.org/ns/oa#>
select ?entityText ?startPos ?endPos ?entityUri ?entityLabel
where {
    []  a oa:Annotation;
    oa:hasBody ?entityUri;
    oa:hasTarget ?z.

    ?z oa:hasSource <{id}>.
    OPTIONAL { ?z oa:hasSelector [oa:exact ?entityText]. }
    OPTIONAL { ?z oa:hasSelector [oa:start ?startPos]. }
    OPTIONAL { ?z oa:hasSelector [oa:end ?endPos]. }

    OPTIONAL { ?entityUri rdfs:label ?entityLabel. FILTER ( lang(?entityLabel) = "en" ) }
}
